name: ubuntu
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        key: cvmfs-apt-cache-${{ runner.os }}
        path: |
          ~/apt/archives/
    - run: |
        mkdir -p ~/apt/archives/
        sudo cp ~/apt/archives/ /var/cache/apt/archives/
    - uses: ./
    - run: |
        cp /var/cache/apt/archives/*.deb ~/apt/archives/
    - name: Test CernVM-FS
      run: |
        echo "### Dump default.local ###"
        cat /etc/cvmfs/default.local
        echo "### Test /cvmfs/lhcb.cern.ch ###"
        ls /cvmfs/lhcb.cern.ch
        echo "### Test /cvmfs/auger.egi.eu ###"
        ls /cvmfs/auger.egi.eu
        echo "### Test /cvmfs/dune.opensciencegrid.org ###"
        ls /cvmfs/dune.opensciencegrid.org
        echo "### Test /cvmfs/sw.hsf.org ###"
        ls /cvmfs/sw.hsf.org
        echo "### Test /cvmfs/sft.cern.ch ###"
        ls /cvmfs/sft.cern.ch
